"""Agent Protocol graph for long-running procurement analysis tasks."""

from __future__ import annotations

import asyncio
from datetime import timedelta
from typing import Any

from deepagents import create_deep_agent
from langchain_core.runnables import RunnableConfig
from opensandbox import SandboxSync

from agent.core.async_sandbox_claims import decode_async_sandbox_claim
from agent.backends.custom_opensandbox import OpenSandboxBackend
from agent.backends.sandbox_proxy import SandboxBackendProxy
from agent.core.config import MAIN_MODEL, SANDBOX_CONFIG
from agent.subagents.loader import load_subagent_configs, resolve_subagent_tools
from agent.tools.chart_generator import create_generate_chart_tool
from agent.tools.mcp_client import load_mcp_tools
from agent.tools.web_search import web_search

_build_lock = asyncio.Lock()
_cached_components: tuple[list[Any], Any, str, list[str]] | None = None
_sandbox_cache: dict[tuple[str, str], SandboxBackendProxy] = {}
_sandbox_locks: dict[tuple[str, str], asyncio.Lock] = {}


def _connect_user_sandbox(sandbox_id: str) -> SandboxBackendProxy:
    sandbox = SandboxSync.connect(sandbox_id, connection_config=SANDBOX_CONFIG)
    # An analysis can run for several minutes. Extend the existing user's TTL
    # so it cannot expire halfway through a legitimate background task.
    sandbox.renew(timedelta(hours=2))
    backend = OpenSandboxBackend(sandbox=sandbox)
    result = backend.execute("echo ok", timeout=30)
    if result.exit_code != 0:
        raise RuntimeError(
            f"User sandbox {sandbox_id} is unavailable: {result.output[:300]}"
        )
    return SandboxBackendProxy(backend)


async def _get_user_sandbox(user_id: str, sandbox_id: str) -> SandboxBackendProxy:
    key = (user_id, sandbox_id)
    lock = _sandbox_locks.setdefault(key, asyncio.Lock())
    async with lock:
        cached = _sandbox_cache.get(key)
        if cached is not None:
            result = await asyncio.to_thread(cached.execute, "echo ok", timeout=30)
            if result.exit_code == 0:
                return cached
            _sandbox_cache.pop(key, None)

        proxy = await asyncio.to_thread(_connect_user_sandbox, sandbox_id)
        _sandbox_cache[key] = proxy
        return proxy


async def _load_components() -> tuple[list[Any], Any, str, list[str]]:
    """Load MCP tools and YAML configuration once per Agent Protocol process."""
    global _cached_components
    if _cached_components is not None:
        return _cached_components

    async with _build_lock:
        if _cached_components is not None:
            return _cached_components

        _, analyst_tools, order_tools, chart_tools = await load_mcp_tools()
        generate_visualization, extra_tools = create_generate_chart_tool(chart_tools)
        available_tools = (
            list(analyst_tools)
            + list(order_tools)
            + list(extra_tools)
            + [generate_visualization, web_search]
        )
        raw = next(
            config
            for config in load_subagent_configs()
            if config.get("name") == "procurement-analyst"
        )
        resolved = resolve_subagent_tools([raw], available_tools)[0]
        _cached_components = (
            resolved["tools"],
            generate_visualization,
            resolved["system_prompt"],
            resolved.get("skills", ["/skills/procurement/"]),
        )
        return _cached_components


async def create_procurement_analyst(config: RunnableConfig):
    """Create the remote analyst graph used by DeepAgents AsyncSubAgent.

    The Agent Protocol server owns task/checkpoint persistence. A signed claim
    generated by the authenticated Web backend binds this run to one user's
    private sandbox; browser/model input cannot choose an arbitrary sandbox.
    """
    tools, generate_visualization, system_prompt, skills = await _load_components()
    configurable = config.get("configurable", {})
    task_id = str(configurable.get("task_id") or configurable.get("thread_id") or "").strip()
    claim = str(configurable.get("sandbox_claim") or "").strip()
    if not task_id or not claim:
        raise RuntimeError("Async task is missing its signed user sandbox binding")

    user_id, sandbox_id = decode_async_sandbox_claim(claim, task_id=task_id)
    sandbox = await _get_user_sandbox(user_id, sandbox_id)
    workspace = f"/analysis/tasks/{task_id}"
    mkdir_result = await asyncio.to_thread(
        sandbox.execute,
        f"mkdir -p {workspace}",
        timeout=30,
    )
    if mkdir_result.exit_code != 0:
        raise RuntimeError(f"Failed to prepare async task workspace: {mkdir_result.output[:300]}")

    # Ensure explicitly-created tools are present even if a YAML name was changed.
    tool_list = list(tools)
    known_names = {getattr(tool, "name", "") for tool in tool_list}
    for tool in (generate_visualization, web_search):
        if getattr(tool, "name", "") not in known_names:
            tool_list.append(tool)

    return create_deep_agent(
        model=MAIN_MODEL,
        system_prompt=(
            system_prompt
            + "\n\n## 当前异步任务的文件隔离规则\n"
            + f"当前用户 ID：{user_id}\n"
            + f"当前任务 ID：{task_id}\n"
            + f"当前任务唯一工作目录：`{workspace}/`\n"
            + "所有报告、图表、临时文件必须写入该目录，禁止写入 /analysis 根目录或其他任务目录。"
            + "最终回复必须给出报告的完整绝对路径，便于主 Agent 从同一用户沙箱下载。"
        ),
        tools=tool_list,
        skills=skills,
        memory=["/AGENTS.md"],
        backend=sandbox,
        name="procurement-analyst",
    )
